### PR TITLE
Adjust listener for kaltura

### LINKED ISSUE #1202: Kaltura Videos on Demo Page Won't Play or Seek
#### Current Behavior
Kaltura Videos on the Demo Page do not play or seek when using the Play/Pause button or Seek range input. 

Perhaps this is related to
https://github.com/cookpete/react-player/pull/1082#issuecomment-759603500
?

Videos are playable if you click the Kaltura video or have the video muted before clicking Play (but you cannot Pause).

#### Expected Behavior
Kaltura Test A and Test B should be able to play or seek. 

#### Steps to Reproduce

1. Use 2.9.0. which just added Kaltura (https://cookpete.com/react-player/ is 2.6.2).
2. Run it locally:
```
git clone https://github.com/CookPete/react-player.git
cd react-player
npm install # or yarn
npm start
open http://localhost:300
```
3. Pick any of the Kaltura options- TestA or TestB.
4. Toggle the Play/Pause button
5. Click on a point in the Seek range after the beginning of the video 

#### Environment
- URL attempting to play: http://localhost:3000/
- Browser: Chrome Version 89.0.4389.90 (Official Build) (x86_64)
- Operating system: MacOS Catalina

#### Other Information
Provided demo videos:
https://cdnapisec.kaltura.com/p/2507381/sp/250738100/embedIframeJs/uiconf_id/44372392/partner_id/2507381?iframeembed=true&playerId=kaltura_player_1605622074&entry_id=1_jz404fbl
https://cdnapisec.kaltura.com/p/2507381/sp/250738100/embedIframeJs/uiconf_id/44372392/partner_id/2507381?iframeembed=true&playerId=kaltura_player_1605622336&entry_id=1_i1jmzcn3

If you add `allow='encrypted-media;autoplay'` to Kaltura.js, the video can be played but not paused.

### PR DESCRIPTION
**Pull request by Yasamato**
Fixes #1202 and related to #1082.

Strangely it is necessary to wait a bit for the player to be ready, even after the `onReady` event fired. Otherwise the added event listeners would just be ignored as there is no warning or error message.

After my adjustments I can now consistently reproduce seeking (in-player and via react-player), play/pause (in-player and via react-player).

Nevertheless there is still no support for:
- playbackRate
- volume update (setting inside the player won't propagate to react-player)
- controls option

Manual investigation (`console.log(this.player.events)`) of the API shows, that the internal player only supports these events:
- "ready"
- "play"
- "pause"
- "ended"
- "timeupdate"
- "progress"
- "error"

### CODE REVIEW

**Comment by kangaree** [comment]
Hi @Yasamato .

Thank you so much for this!!!

I'm confirming you've fixed the seeking action. 

With this PR, I'm having some trouble with the Play/Pause toggle, but I believe this is fixed if you add "autoplay" to the Kaltura iframe:

`<iframe
  ref={this.ref}
  src={this.props.url}
  frameBorder="0"
  scrolling="no"
  style={style}
  allowFullScreen
  allow="encrypted-media;autoplay"
  referrerPolicy="no-referrer-when-downgrade"
/>`

**Comment by kangaree** [comment]
I'm on a Mac and I use Chrome as a browser.

File: src/players/Kaltura.js [hunk 1]
```diff
@@ -16,39 +16,40 @@ export default class Kaltura extends Component {
...
           this.props.onReady()
-        })
+        }, 500)
       })
     }, this.props.onError)
   }
 
+  load (url) {
+    // wait what?
+  }
```
[the remark this answers is not in the document]
Comment (Yasamato) [reply src/players/Kaltura.js]: I looked again over it, but if you take a closer look over the original and the modified code from me, there is no use of the url parameter. When you change the video from one to another I doubt it ever get's called tbh... did not check nor validate it thou.

Moved it back to `load` and calling it now in `componentDidMount`

File: src/players/Kaltura.js [hunk 2]
```diff
@@ -16,39 +16,40 @@ export default class Kaltura extends Component {
 
   componentDidMount () {
     this.props.onMount && this.props.onMount(this)
+    this.load()
```
Comment (cookpete) [inline src/players/Kaltura.js:19]: This needs to be removed. `load` is called when needed by the parent `Player`.

File: src/players/Kaltura.js [hunk 3]
```diff
@@ -16,39 +16,40 @@ export default class Kaltura extends Component {
...
-          if (this.duration) {
-            this.secondsLoaded = this.duration * percent
-          }
-        })
-        this.player.setLoop(this.props.loop)
-        if (this.props.muted) {
-          this.player.mute()
-        }
+        // an arbitrary timeout is is required,
+        // otherwise the eventListeners won't work
```
Comment (cookpete) [inline src/players/Kaltura.js:28]:
```suggestion
        // An arbitrary timeout is required otherwise
        // the event listeners won’t work
```

**Comment by cookpete** [comment]
Published in `2.10.0`
